import { ANDROIDHOMEPAGE } from "../HOMEPAGE/HomePage.js";

const ANDROIDMUSICPAGES=(DIV,ADVANCE)=>{

    //DECLARATION
    const STYLED=ADVANCE.STYLED;
    const CLEAR=ADVANCE.CLEAR;
    const ADD=ADVANCE.ADDPACKAGE;
    const DISPLAY=ADVANCE.DISPLAYDATA;
    const HEADER=ADVANCE.HEADER;
    const FOOTER=ADVANCE.FOOTER;
    const HOMEICON=ADVANCE.HOMEICON;
    const GRIDICON=ADVANCE.GRIDICON;
    const MUSICICON=ADVANCE.MUSICICON;
    const HEARTICON=ADVANCE.HEARTICON;
    const USERICON=ADVANCE.USERICON;
    const SETTINGSICON=ADVANCE.SETTINGSICON;
    const NOTIFICATIONICON=ADVANCE.NOTIFICATIONICON;
    const PROFILEICON=ADVANCE.PROFILEICON;
    const HORIZONTALSCROLLINGDIV=ADVANCE.HORIZONTALSCROLLINGDIV;
    const BACKICON=ADVANCE.BACKICON;
    const MENUDIV=ADVANCE.MENUDIV;
    const SEARCHINPUT=ADVANCE.SEARCHINPUT;

    //STYLE SECTION
    STYLED(BACKICON,'marginLeft','0.2rem');
    STYLED(BACKICON,'marginRight','1rem');
    STYLED(HEADER,'left','50px');
    STYLED(HEADER,'right','0');
    STYLED(HEADER,'width','auto');
    STYLED(MENUDIV,'width','50px');
    STYLED(FOOTER,'left','50px');
    STYLED(HORIZONTALSCROLLINGDIV,'top','50px');
    STYLED(HORIZONTALSCROLLINGDIV,'left','50px');
    STYLED(HORIZONTALSCROLLINGDIV,'bottom','50px');
    STYLED(SEARCHINPUT,'marginTop','auto');
    STYLED(SEARCHINPUT,'marginBottom','auto');
    STYLED(SEARCHINPUT,'marginLeft','2rem');
    STYLED(SEARCHINPUT,'width','70%');
    STYLED(MUSICICON,'marginLeft','auto');
    STYLED(MUSICICON,'marginRight','1rem');

    CLEAR(DIV);

    CLEAR(HEADER);

    CLEAR(FOOTER);

    CLEAR(HORIZONTALSCROLLINGDIV)

    ADD(DIV,HEADER);

    ADD(HEADER,SEARCHINPUT);

    ADD(HEADER,MUSICICON);

    ADD(DIV,HORIZONTALSCROLLINGDIV);

    ADD(DIV,MENUDIV);

    ADD(DIV,FOOTER);

    ADD(MENUDIV,BACKICON);

    //FUNCTIONS SECTION
    BACKICON.addEventListener('click',()=>{

        ANDROIDHOMEPAGE(DIV,ADVANCE)

    })

  


}

export{ANDROIDMUSICPAGES}