const WHITEICONS=`../ASSETS/ICONS/WHITE/`;
const BLACKICONS=`../ASSETS/ICONS/BLACK`;
const TEALICONS=`../ASSETS/ICONS/TEAL/`;
const VIDEOSAPI=`../ASSETS/VIDEOS/`;
const SOUNDSAPI=`../ASSETS/SOUNDS/`;
const IMAGESAPI=`../ASSETS/IMAGES/`;
const COUNTRIESAPI=`../DATABASE/Countries.json`;


export{WHITEICONS,BLACKICONS,TEALICONS,VIDEOSAPI,SOUNDSAPI,IMAGESAPI,COUNTRIESAPI}