const LOGINCREATEACCOUNTBUTTON=document.createElement('button');
LOGINCREATEACCOUNTBUTTON.innerHTML='Create Account';
//STYLES
LOGINCREATEACCOUNTBUTTON.style.position='relative';
LOGINCREATEACCOUNTBUTTON.style.width='95%';
LOGINCREATEACCOUNTBUTTON.style.height='50px';
LOGINCREATEACCOUNTBUTTON.style.minHeight='16px';
LOGINCREATEACCOUNTBUTTON.style.maxHeight='50px';
LOGINCREATEACCOUNTBUTTON.style.background='teal';
LOGINCREATEACCOUNTBUTTON.style.marginTop='1rem';
LOGINCREATEACCOUNTBUTTON.style.marginBottom='1rem';
LOGINCREATEACCOUNTBUTTON.style.left='2%';
LOGINCREATEACCOUNTBUTTON.style.textAlign='center';
LOGINCREATEACCOUNTBUTTON.style.display='block';
LOGINCREATEACCOUNTBUTTON.style.borderRadius='5px';
LOGINCREATEACCOUNTBUTTON.style.color='white';
LOGINCREATEACCOUNTBUTTON.style.border='none';


export{LOGINCREATEACCOUNTBUTTON};