const CREATEACCOUNTUSERNAMEINPUT=document.createElement('input');
CREATEACCOUNTUSERNAMEINPUT.placeholder='Enter UserName';
CREATEACCOUNTUSERNAMEINPUT.type='text';
//STYLES
CREATEACCOUNTUSERNAMEINPUT.style.position='relative';
CREATEACCOUNTUSERNAMEINPUT.style.width='95%';
CREATEACCOUNTUSERNAMEINPUT.style.height='32px';
CREATEACCOUNTUSERNAMEINPUT.style.minHeight='16px';
CREATEACCOUNTUSERNAMEINPUT.style.maxHeight='32px';
CREATEACCOUNTUSERNAMEINPUT.style.background='#00000080';
CREATEACCOUNTUSERNAMEINPUT.style.marginTop='1rem';
CREATEACCOUNTUSERNAMEINPUT.style.marginBottom='1rem';
CREATEACCOUNTUSERNAMEINPUT.style.left='2%';
CREATEACCOUNTUSERNAMEINPUT.style.textAlign='left';
CREATEACCOUNTUSERNAMEINPUT.style.display='block';
CREATEACCOUNTUSERNAMEINPUT.style.borderRadius='5px';
CREATEACCOUNTUSERNAMEINPUT.style.color='white';
CREATEACCOUNTUSERNAMEINPUT.style.border='none';
CREATEACCOUNTUSERNAMEINPUT.style.outline = 'none';


export{CREATEACCOUNTUSERNAMEINPUT};