import { ANDROIDCATERGORY } from "../CATERGORYPAGE/CatergoryPage.js";

const ANDROIDHOMEPAGE=(DIV,ADVANCE)=>{


    CLEAR(DIV);

    CLEAR(HEADER);


    //STYLES ZONE
    STYLED(DIV,'background',ADVANCE.COLOURS.TEAL);
    STYLED(HOMEICON,'marginLeft','0.2rem');
    STYLED(HOMEICON,'marginRight','1rem');
    STYLED(NOTIFICATIONICON,'marginLeft','auto');
    STYLED(NOTIFICATIONICON,'marginRight','1rem');
    STYLED(PROFILEICON,'marginLeft','1rem');
    STYLED(PROFILEICON,'marginRight','1rem');
    

  
    //LAYOUT ZONE
    ADD(DIV,HORIZONTALSCROLLINGDIV);

    ADD(DIV,HEADER);

    ADD(HEADER,HOMEICON);

    ADD(HEADER,NOTIFICATIONICON);

    ADD(HEADER,PROFILEICON);

    ADD(DIV,FOOTER);

    ADD(FOOTER,GRIDICON);

    ADD(FOOTER,MUSICICON);

    ADD(FOOTER,HEARTICON);

    ADD(FOOTER,USERICON);

    ADD(FOOTER,SETTINGSICON);

    //FUNCTIONS

    GRIDICON.addEventListener('click',()=>{

        ANDROIDCATERGORY(DIV,ADVANCE);        

    })

    


}

export{ANDROIDHOMEPAGE}