import { ANDROIDCATERGORY } from "../CATERGORYPAGE/CatergoryPage.js";
import { ANDROIDMUSICPAGES } from "../MUSICPAGE/MusicPage.js";

const ANDROIDHOMEPAGE=(DIV,ADVANCE)=>{

    //DECLARATION
    const STYLED=ADVANCE.STYLED;
    const CLEAR=ADVANCE.CLEAR;
    const ADD=ADVANCE.ADDPACKAGE;
    const APPNAME=ADVANCE.LOGINAPPNAME;
    const DISPLAY=ADVANCE.DISPLAYDATA;
    const HEADER=ADVANCE.HEADER;
    const FOOTER=ADVANCE.FOOTER;
    const HOMEICON=ADVANCE.HOMEICON;
    const GRIDICON=ADVANCE.GRIDICON;
    const MUSICICON=ADVANCE.MUSICICON;
    const HEARTICON=ADVANCE.HEARTICON;
    const USERICON=ADVANCE.USERICON;
    const SETTINGSICON=ADVANCE.SETTINGSICON;
    const NOTIFICATIONICON=ADVANCE.NOTIFICATIONICON;
    const PROFILEICON=ADVANCE.PROFILEICON;
    const HORIZONTALSCROLLINGDIV=ADVANCE.HORIZONTALSCROLLINGDIV;

    CLEAR(DIV);

    CLEAR(HEADER);

    DISPLAY(APPNAME,'Tune Ziki');

    //STYLES ZONE
    STYLED(DIV,'background',ADVANCE.COLOURS.TEAL);
    STYLED(HOMEICON,'marginLeft','0.2rem');
    STYLED(HOMEICON,'marginRight','1rem');
    STYLED(NOTIFICATIONICON,'marginLeft','auto');
    STYLED(NOTIFICATIONICON,'marginRight','1rem');
    STYLED(PROFILEICON,'marginLeft','1rem');
    STYLED(PROFILEICON,'marginRight','1rem');
    STYLED(APPNAME,'marginLeft','1rem');
    STYLED(APPNAME,'marginRight','1rem');
    STYLED(APPNAME,'marginTop','auto');
    STYLED(APPNAME,'marginBottom','auto');
    STYLED(APPNAME,'fontSize','20px');
    STYLED(APPNAME,'color','white');
    
    //LAYOUT ZONE
    ADD(DIV,HORIZONTALSCROLLINGDIV);

    ADD(DIV,HEADER);

    ADD(HEADER,APPNAME);

    ADD(HEADER,NOTIFICATIONICON);

    ADD(HEADER,PROFILEICON);

    ADD(DIV,FOOTER);

    ADD(FOOTER,GRIDICON);

    ADD(FOOTER,MUSICICON);

    ADD(FOOTER,HEARTICON);

    ADD(FOOTER,USERICON);

    ADD(FOOTER,SETTINGSICON);

    //FUNCTIONS

    GRIDICON.addEventListener('click',()=>{

        ANDROIDCATERGORY(DIV,ADVANCE);        

    })
    
    MUSICICON.addEventListener('click',()=>{

        ANDROIDMUSICPAGES(DIV,ADVANCE);        

    })

    


}

export{ANDROIDHOMEPAGE}