import { ANDROIDHOMEPAGE } from "../HOMEPAGE/HomePage.js";

const ANDROIDUSERPROFILEPAGE=(DIV,ADVANCE)=>{

    //DECLARATION
    const STYLED=ADVANCE.STYLED;
    const CLEAR=ADVANCE.CLEAR;
    const ADD=ADVANCE.ADDPACKAGE;
    const HEADER=ADVANCE.HEADER;
    const HORIZONTALSCROLLINGDIV=ADVANCE.HORIZONTALSCROLLINGDIV;
    const BACKICON=ADVANCE.BACKICON;
    const GRIDICON=ADVANCE.PROFILEICON;
     
    
    CLEAR(DIV);

    CLEAR(HEADER);

        
        
    //STYLES ZONE
    STYLED(BACKICON,'marginLeft','0.2rem');
    STYLED(BACKICON,'marginRight','1rem');
    STYLED(GRIDICON,'marginLeft','auto');
    STYLED(GRIDICON,'marginRight','1rem');
 
        


    //LAYOUT ZONE
    ADD(DIV,HORIZONTALSCROLLINGDIV);

    ADD(DIV,HEADER);

    ADD(HEADER,BACKICON);

    ADD(HEADER,GRIDICON);

        

        

    

    //FUNCTIONS
    BACKICON.addEventListener('click',()=>{

        ANDROIDHOMEPAGE(DIV,ADVANCE)

    })


}

export{ANDROIDUSERPROFILEPAGE}