const HORIZONTALSCROLLINGDIV=document.createElement('div');
//STYLES
HORIZONTALSCROLLINGDIV.style.position='absolute';
HORIZONTALSCROLLINGDIV.style.width='100%';
HORIZONTALSCROLLINGDIV.style.height='auto';
HORIZONTALSCROLLINGDIV.style.top='0';
HORIZONTALSCROLLINGDIV.style.bottom='0';
HORIZONTALSCROLLINGDIV.style.display='block';
HORIZONTALSCROLLINGDIV.style.overflowX='hidden';
HORIZONTALSCROLLINGDIV.style.overflowY='auto';
HORIZONTALSCROLLINGDIV.style.background='#00000080';



export{HORIZONTALSCROLLINGDIV};